apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: server
        image: gkulshre/coit-home-commerce:adservice_v1
        ports:
        - containerPort: 9555
       
